/*
###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Tue Dec 17 19:42:37 2024
#  Design:            int_pe
#  Command:           saveNetlist /home/jjt/innovus_file/open_source/out/int_pe-rpt/int_pe-post.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : T-2022.03-SP2
// Date      : Tue Dec 17 18:51:51 2024
/////////////////////////////////////////////////////////////
module int_pe (
	clk, 
	rst, 
	fsm_out_select_in, 
	left_in, 
	top_in, 
	right_out, 
	bottom_out);
   input clk;
   input rst;
   input fsm_out_select_in;
   input [3:0] left_in;
   input [23:0] top_in;
   output [3:0] right_out;
   output [23:0] bottom_out;

   // Internal wires
   wire FE_PSN32_n209;
   wire FE_PSN31_n190;
   wire FE_PSN30_n357;
   wire FE_PSN29_n47;
   wire FE_PSN28_accumulator_reg_3;
   wire FE_PSN26_FE_RN_4;
   wire FE_PSN24_top_in_reg_1;
   wire FE_PSN23_FE_RN_1;
   wire FE_OCPN22_top_in_reg_0;
   wire FE_OCPN21_n300;
   wire FE_OCPN20_top_in_reg_2;
   wire FE_RN_91_0;
   wire FE_RN_90_0;
   wire FE_RN_89_0;
   wire FE_RN_88_0;
   wire FE_RN_87_0;
   wire FE_RN_11;
   wire FE_OCPN19_top_in_reg_3;
   wire FE_RN_86_0;
   wire FE_RN_84_0;
   wire FE_RN_83_0;
   wire FE_RN_82_0;
   wire FE_RN_10;
   wire FE_RN_81_0;
   wire FE_RN_9;
   wire FE_RN_80_0;
   wire FE_OCPN18_n204;
   wire FE_RN_79_0;
   wire FE_RN_8;
   wire FE_OCPN17_n354;
   wire FE_RN_5;
   wire FE_RN_78_0;
   wire FE_RN_77_0;
   wire FE_RN_76_0;
   wire FE_RN_75_0;
   wire FE_RN_74_0;
   wire FE_RN_3;
   wire FE_RN_73_0;
   wire FE_RN_71_0;
   wire FE_RN_68_0;
   wire FE_RN_67_0;
   wire FE_RN_65_0;
   wire FE_RN_64_0;
   wire FE_RN_63_0;
   wire CTS_8;
   wire CTS_7;
   wire CTS_6;
   wire CTS_10;
   wire CTS_9;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire CTS_5;
   wire CTS_4;
   wire FE_RN_61_0;
   wire FE_RN_60_0;
   wire FE_RN_59_0;
   wire FE_RN_56_0;
   wire FE_RN_55_0;
   wire FE_RN_54_0;
   wire FE_RN_53_0;
   wire FE_RN_51_0;
   wire FE_RN_50_0;
   wire FE_RN_49_0;
   wire FE_RN_48_0;
   wire FE_RN_47_0;
   wire FE_RN_7;
   wire FE_RN_4;
   wire FE_RN_45_0;
   wire FE_RN_44_0;
   wire FE_RN_43_0;
   wire FE_RN_6;
   wire FE_RN_40_0;
   wire FE_RN_39_0;
   wire FE_RN_2;
   wire FE_RN_37_0;
   wire FE_RN_35_0;
   wire FE_RN_34_0;
   wire FE_RN_1;
   wire FE_RN_33_0;
   wire FE_RN_31_0;
   wire FE_RN_30_0;
   wire FE_RN_29_0;
   wire FE_RN_26_0;
   wire FE_RN_25_0;
   wire FE_RN_21_0;
   wire FE_RN_18_0;
   wire FE_RN_15_0;
   wire FE_RN_14_0;
   wire FE_RN_12_0;
   wire FE_RN_11_0;
   wire FE_RN_10_0;
   wire FE_RN_9_0;
   wire FE_RN_8_0;
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_RN_3_0;
   wire FE_RN_0_0;
   wire N2;
   wire N3;
   wire N4;
   wire N5;
   wire N6;
   wire N7;
   wire N8;
   wire N9;
   wire N10;
   wire N11;
   wire N12;
   wire N13;
   wire N14;
   wire N15;
   wire N16;
   wire N17;
   wire N18;
   wire N19;
   wire N20;
   wire N21;
   wire N22;
   wire N23;
   wire N24;
   wire N25;
   wire n31;
   wire n35;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n62;
   wire n63;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n70;
   wire n72;
   wire n73;
   wire n74;
   wire n78;
   wire n81;
   wire n83;
   wire n84;
   wire n85;
   wire n88;
   wire n90;
   wire n91;
   wire n95;
   wire n96;
   wire n97;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n122;
   wire n123;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n177;
   wire n178;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire [23:0] accumulator_reg;
   wire [3:0] top_in_reg;

   BUFX2 PostRFE_PSC32_n209 (.A(n209),
	.Y(FE_PSN32_n209));
   BUFX4 PostRFE_PSC31_n190 (.A(n190),
	.Y(FE_PSN31_n190));
   BUFX4 PostRFE_PSC30_n357 (.A(n357),
	.Y(FE_PSN30_n357));
   BUFX2 PostRFE_PSC29_n47 (.A(n47),
	.Y(FE_PSN29_n47));
   BUFX2 PostRFE_PSC28_accumulator_reg_3 (.A(accumulator_reg[3]),
	.Y(FE_PSN28_accumulator_reg_3));
   BUFX2 PostRFE_PSC26_FE_RN_4 (.A(FE_RN_4),
	.Y(FE_PSN26_FE_RN_4));
   BUFX2 PostRFE_PSC24_top_in_reg_1 (.A(top_in_reg[1]),
	.Y(FE_PSN24_top_in_reg_1));
   BUFX4 PostRFE_PSC23_FE_RN_1 (.A(FE_RN_1),
	.Y(FE_PSN23_FE_RN_1));
   BUFX2 CTSFE_OCPC22_top_in_reg_0 (.A(top_in_reg[0]),
	.Y(FE_OCPN22_top_in_reg_0));
   BUFX2 CTSFE_OCPC21_n300 (.A(n300),
	.Y(FE_OCPN21_n300));
   BUFX2 CTSFE_OCPC20_top_in_reg_2 (.A(top_in_reg[2]),
	.Y(FE_OCPN20_top_in_reg_2));
   NAND2X1 CTSFE_RC_187_0 (.A(n228),
	.B(n227),
	.Y(FE_RN_91_0));
   OAI21X1 CTSFE_RC_186_0 (.A(FE_RN_91_0),
	.B(n354),
	.C(n271),
	.Y(n316));
   NAND2X1 CTSFE_RC_185_0 (.A(n205),
	.B(n204),
	.Y(FE_RN_88_0));
   NOR2X1 CTSFE_RC_184_0 (.A(n205),
	.B(n204),
	.Y(FE_RN_89_0));
   AOI21X1 CTSFE_RC_183_0 (.A(FE_RN_4),
	.B(n389),
	.C(n390),
	.Y(FE_RN_90_0));
   OAI21X1 CTSFE_RC_182_0 (.A(FE_RN_90_0),
	.B(FE_RN_89_0),
	.C(FE_RN_88_0),
	.Y(n370));
   AOI22X1 CTSFE_RC_181_0 (.A(n259),
	.B(FE_RN_5_0),
	.C(FE_RN_84_0),
	.D(n256),
	.Y(FE_RN_86_0));
   NAND2X1 CTSFE_RC_180_0 (.A(FE_RN_9),
	.B(n264),
	.Y(FE_RN_87_0));
   OAI21X1 CTSFE_RC_179_0 (.A(FE_RN_87_0),
	.B(n267),
	.C(FE_RN_68_0),
	.Y(FE_RN_45_0));
   NAND2X1 CTSPlaceFE_RC_106_0_dup (.A(FE_RN_50_0),
	.B(FE_RN_51_0),
	.Y(FE_RN_11));
   BUFX2 CTSFE_OCPC19_top_in_reg_3 (.A(top_in_reg[3]),
	.Y(FE_OCPN19_top_in_reg_3));
   OR2X2 CTSFE_RC_178_0 (.A(n259),
	.B(n258),
	.Y(FE_RN_82_0));
   OAI21X1 CTSFE_RC_177_0 (.A(n256),
	.B(n259),
	.C(FE_RN_82_0),
	.Y(n286));
   INVX2 CTSFE_RC_176_0 (.A(n258),
	.Y(FE_RN_83_0));
   NOR2X1 CTSFE_RC_175_0 (.A(FE_RN_83_0),
	.B(n116),
	.Y(FE_RN_84_0));
   NAND2X1 CTSFE_RC_172_0 (.A(n66),
	.B(FE_RN_86_0),
	.Y(n288));
   INVX2 CTSPlaceFE_RC_90_0_dup (.A(right_out[0]),
	.Y(FE_RN_10));
   INVX1 CTSFE_RC_171_0 (.A(n252),
	.Y(FE_RN_81_0));
   AOI22X1 CTSFE_RC_170_0 (.A(top_in[23]),
	.B(n252),
	.C(FE_RN_81_0),
	.D(n338),
	.Y(n339));
   AOI21X1 CTSU379_dup (.A(n97),
	.B(n226),
	.C(n243),
	.Y(FE_RN_9));
   XOR2X1 CTSFE_RC_169_0 (.A(n316),
	.B(n274),
	.Y(n275));
   XNOR2X1 CTSFE_RC_168_0 (.A(n328),
	.B(n327),
	.Y(n329));
   INVX2 CTSFE_RC_167_0 (.A(fsm_out_select_in),
	.Y(FE_RN_80_0));
   AOI22X1 CTSFE_RC_166_0 (.A(top_in[22]),
	.B(FE_RN_80_0),
	.C(fsm_out_select_in),
	.D(n297),
	.Y(n298));
   BUFX2 CTSFE_OCPC18_n204 (.A(n204),
	.Y(FE_OCPN18_n204));
   OR2X2 CTSFE_RC_165_0 (.A(n279),
	.B(n323),
	.Y(FE_RN_79_0));
   NAND2X1 CTSFE_RC_164_0 (.A(FE_RN_79_0),
	.B(FE_RN_77_0),
	.Y(n328));
   OAI21X1 CTSPlaceFE_RC_68_0_dup (.A(n114),
	.B(FE_RN_37_0),
	.C(FE_RN_2),
	.Y(FE_RN_8));
   BUFX4 CTSFE_OCPC17_n354 (.A(n354),
	.Y(FE_OCPN17_n354));
   AOI21X1 CTSPlaceFE_RC_128_0_dup (.A(FE_RN_4),
	.B(n389),
	.C(n390),
	.Y(FE_RN_5));
   AOI21X1 CTSFE_RC_163_0 (.A(n291),
	.B(FE_RN_3_0),
	.C(FE_RN_15_0),
	.Y(FE_RN_78_0));
   AOI21X1 CTSFE_RC_162_0 (.A(FE_RN_78_0),
	.B(FE_RN_30_0),
	.C(FE_RN_14_0),
	.Y(FE_RN_12_0));
   NAND2X1 CTSFE_RC_161_0 (.A(n277),
	.B(FE_RN_65_0),
	.Y(n324));
   INVX2 CTSFE_RC_160_0 (.A(n279),
	.Y(FE_RN_75_0));
   AND2X2 CTSFE_RC_159_0 (.A(FE_RN_75_0),
	.B(n277),
	.Y(FE_RN_76_0));
   NAND2X1 CTSFE_RC_158_0 (.A(FE_RN_76_0),
	.B(FE_RN_65_0),
	.Y(FE_RN_77_0));
   OAI21X1 CTSFE_RC_156_0 (.A(FE_RN_55_0),
	.B(FE_RN_12_0),
	.C(FE_RN_54_0),
	.Y(n337));
   OR2X2 CTSFE_RC_155_0 (.A(n187),
	.B(n186),
	.Y(FE_RN_74_0));
   XNOR2X1 CTSFE_RC_154_0 (.A(FE_RN_74_0),
	.B(FE_PSN28_accumulator_reg_3),
	.Y(n199));
   OAI21X1 CTSU416_dup (.A(n103),
	.B(n354),
	.C(n271),
	.Y(FE_RN_3));
   AOI21X1 CTSFE_RC_153_0 (.A(n370),
	.B(FE_RN_7),
	.C(FE_RN_8),
	.Y(n357));
   NAND2X1 CTSFE_RC_152_0 (.A(n395),
	.B(n402),
	.Y(FE_RN_73_0));
   NAND2X1 CTSFE_RC_151_0 (.A(n47),
	.B(FE_RN_73_0),
	.Y(FE_RN_4));
   INVX2 CTSFE_RC_150_0 (.A(n188),
	.Y(n68));
   AND2X2 CTSFE_RC_148_0 (.A(n68),
	.B(accumulator_reg[2]),
	.Y(n200));
   INVX4 CTSFE_RC_147_0 (.A(FE_RN_71_0),
	.Y(n185));
   XOR2X1 CTSFE_RC_146_0 (.A(n109),
	.B(accumulator_reg[4]),
	.Y(FE_RN_71_0));
   INVX2 CTSFE_RC_144_0 (.A(n307),
	.Y(FE_RN_67_0));
   OAI21X1 CTSFE_RC_143_0 (.A(FE_RN_31_0),
	.B(FE_RN_67_0),
	.C(n54),
	.Y(FE_RN_68_0));
   INVX4 CTSFE_RC_139_0 (.A(FE_RN_6),
	.Y(n354));
   INVX2 CTSFE_RC_138_0 (.A(n105),
	.Y(FE_RN_64_0));
   NAND2X1 CTSFE_RC_137_0 (.A(FE_RN_6),
	.B(FE_RN_64_0),
	.Y(FE_RN_65_0));
   INVX1 CTSFE_RC_135_0 (.A(n252),
	.Y(FE_RN_63_0));
   AOI22X1 CTSFE_RC_134_0 (.A(top_in[15]),
	.B(n252),
	.C(FE_RN_63_0),
	.D(n313),
	.Y(n314));
   NOR3X1 CTSFE_RC_133_0 (.A(FE_RN_49_0),
	.B(n186),
	.C(n187),
	.Y(n172));
   AND2X2 CTSFE_RC_130_0 (.A(FE_PSN32_n209),
	.B(n208),
	.Y(n372));
   NAND2X1 CTSFE_RC_129_0 (.A(n209),
	.B(n208),
	.Y(FE_RN_2));
   CLKBUF1 CTS_ccl_a_buf_00020 (.A(CTS_8),
	.Y(CTS_7));
   CLKBUF1 CTS_ccl_a_buf_00018 (.A(CTS_8),
	.Y(CTS_6));
   CLKBUF1 CTS_ccl_a_buf_00016 (.A(CTS_8),
	.Y(CTS_10));
   CLKBUF1 CTS_ccl_a_buf_00014 (.A(CTS_8),
	.Y(CTS_9));
   CLKBUF1 CTS_ccl_a_buf_00030 (.A(clk),
	.Y(CTS_8));
   CLKBUF1 CTS_ccl_a_buf_00024 (.A(CTS_3),
	.Y(CTS_2));
   CLKBUF1 CTS_ccl_a_buf_00022 (.A(CTS_3),
	.Y(CTS_1));
   CLKBUF1 CTS_ccl_a_buf_00012 (.A(CTS_3),
	.Y(CTS_5));
   CLKBUF1 CTS_ccl_a_buf_00010 (.A(CTS_3),
	.Y(CTS_4));
   CLKBUF1 CTS_ccl_a_buf_00028 (.A(clk),
	.Y(CTS_3));
   XNOR2X1 PlaceFE_RC_127_0 (.A(FE_RN_61_0),
	.B(accumulator_reg[1]),
	.Y(n193));
   INVX2 PlaceFE_RC_126_0 (.A(accumulator_reg[1]),
	.Y(FE_RN_60_0));
   NAND2X1 PlaceFE_RC_125_0 (.A(right_out[0]),
	.B(top_in_reg[1]),
	.Y(FE_RN_61_0));
   NOR2X1 PlaceFE_RC_124_0 (.A(FE_RN_60_0),
	.B(FE_RN_61_0),
	.Y(n201));
   OR2X2 PlaceFE_RC_123_0 (.A(n206),
	.B(n207),
	.Y(n377));
   NOR2X1 PlaceFE_RC_122_0 (.A(n206),
	.B(n207),
	.Y(FE_RN_59_0));
   NOR2X1 PlaceFE_RC_121_0 (.A(FE_RN_59_0),
	.B(FE_RN_56_0),
	.Y(n35));
   XOR2X1 PlaceFE_RC_120_0 (.A(n261),
	.B(n260),
	.Y(n262));
   XOR2X1 PlaceFE_RC_119_0 (.A(n251),
	.B(n250),
	.Y(n253));
   INVX4 PlaceFE_RC_118_0 (.A(right_out[1]),
	.Y(n190));
   OR2X2 PlaceFE_RC_116_0 (.A(FE_PSN31_n190),
	.B(n170),
	.Y(n174));
   NOR2X1 PlaceFE_RC_115_0 (.A(n208),
	.B(FE_PSN32_n209),
	.Y(FE_RN_56_0));
   INVX2 PlaceFE_RC_112_0 (.A(FE_RN_35_0),
	.Y(FE_RN_53_0));
   NAND2X1 PlaceFE_RC_111_0 (.A(FE_RN_53_0),
	.B(FE_RN_40_0),
	.Y(FE_RN_54_0));
   INVX2 PlaceFE_RC_110_0 (.A(FE_RN_40_0),
	.Y(FE_RN_55_0));
   INVX2 PlaceFE_RC_108_0 (.A(n209),
	.Y(FE_RN_50_0));
   INVX2 PlaceFE_RC_107_0 (.A(n208),
	.Y(FE_RN_51_0));
   NAND2X1 PlaceFE_RC_106_0 (.A(FE_RN_50_0),
	.B(FE_RN_51_0),
	.Y(n371));
   XNOR2X1 PlaceFE_RC_103_0 (.A(FE_RN_45_0),
	.B(n311),
	.Y(n313));
   XOR2X1 PlaceFE_RC_102_0 (.A(FE_OCPN21_n300),
	.B(n223),
	.Y(n224));
   INVX2 PlaceFE_RC_101_0 (.A(accumulator_reg[3]),
	.Y(FE_RN_49_0));
   NAND2X1 PlaceFE_RC_98_0 (.A(FE_RN_47_0),
	.B(n358),
	.Y(n284));
   INVX2 PlaceFE_RC_97_0 (.A(n115),
	.Y(FE_RN_47_0));
   AND2X2 PlaceFE_RC_96_0 (.A(n358),
	.B(FE_RN_47_0),
	.Y(FE_RN_48_0));
   NAND2X1 PlaceFE_RC_95_0 (.A(FE_RN_0_0),
	.B(FE_RN_48_0),
	.Y(FE_RN_3_0));
   AND2X2 PlaceU88_dup (.A(n377),
	.B(FE_RN_11),
	.Y(FE_RN_7));
   XNOR2X1 PlaceFE_RC_94_0 (.A(n304),
	.B(n303),
	.Y(n305));
   INVX2 PlaceFE_RC_91_0 (.A(top_in_reg[1]),
	.Y(n187));
   INVX1 PlaceFE_RC_90_0 (.A(right_out[0]),
	.Y(n191));
   AND2X2 PlaceFE_RC_87_0 (.A(right_out[1]),
	.B(top_in_reg[2]),
	.Y(n136));
   NAND2X1 PlaceFE_RC_85_0 (.A(n68),
	.B(FE_RN_44_0),
	.Y(FE_RN_43_0));
   INVX2 PlaceFE_RC_84_0 (.A(accumulator_reg[2]),
	.Y(FE_RN_44_0));
   OAI21X1 PlaceFE_RC_83_0 (.A(n68),
	.B(FE_RN_44_0),
	.C(FE_RN_43_0),
	.Y(n197));
   OAI21X1 PlaceFE_RC_81_0_dup (.A(n284),
	.B(FE_PSN23_FE_RN_1),
	.C(n215),
	.Y(FE_RN_6));
   OAI21X1 PlaceFE_RC_81_0 (.A(n284),
	.B(FE_PSN23_FE_RN_1),
	.C(n215),
	.Y(n226));
   AND2X2 PlaceFE_RC_80_0 (.A(n212),
	.B(n211),
	.Y(n365));
   NAND2X1 PlaceFE_RC_79_0 (.A(n212),
	.B(n211),
	.Y(n112));
   OR2X2 PlaceFE_RC_78_0 (.A(n332),
	.B(n331),
	.Y(FE_RN_40_0));
   INVX2 PlaceFE_RC_75_0 (.A(FE_RN_21_0),
	.Y(FE_RN_39_0));
   NAND3X1 PlaceFE_RC_74_0 (.A(FE_RN_5_0),
	.B(FE_RN_39_0),
	.C(n278),
	.Y(n289));
   NAND2X1 PlaceFE_RC_73_0 (.A(n205),
	.B(n204),
	.Y(n62));
   NOR2X1 PlaceFE_RC_69_0 (.A(n209),
	.B(n208),
	.Y(FE_RN_37_0));
   OAI21X1 PlaceFE_RC_68_0 (.A(n114),
	.B(FE_RN_37_0),
	.C(FE_RN_2),
	.Y(n210));
   NAND2X1 PlaceFE_RC_67_0 (.A(n67),
	.B(FE_RN_12_0),
	.Y(n333));
   INVX2 PlaceFE_RC_66_0 (.A(n67),
	.Y(FE_RN_34_0));
   NOR2X1 PlaceFE_RC_65_0 (.A(FE_RN_34_0),
	.B(n331),
	.Y(FE_RN_35_0));
   AOI21X1 PlaceU368_dup (.A(n370),
	.B(n35),
	.C(n210),
	.Y(FE_RN_1));
   INVX2 PlaceFE_RC_62_0 (.A(fsm_out_select_in),
	.Y(FE_RN_33_0));
   AOI22X1 PlaceFE_RC_61_0 (.A(top_in[17]),
	.B(FE_RN_33_0),
	.C(fsm_out_select_in),
	.D(n329),
	.Y(n330));
   OAI21X1 PlaceFE_RC_60_0 (.A(n265),
	.B(n104),
	.C(n264),
	.Y(n308));
   AND2X2 PlaceFE_RC_59_0 (.A(n264),
	.B(n104),
	.Y(FE_RN_31_0));
   NAND2X1 PlaceFE_RC_56_0 (.A(FE_PSN30_n357),
	.B(n291),
	.Y(FE_RN_30_0));
   NAND2X1 PlaceFE_RC_54_0 (.A(n207),
	.B(n206),
	.Y(n114));
   INVX2 PlaceFE_RC_53_0 (.A(fsm_out_select_in),
	.Y(FE_RN_29_0));
   AOI22X1 PlaceFE_RC_52_0 (.A(top_in[13]),
	.B(FE_RN_29_0),
	.C(fsm_out_select_in),
	.D(n305),
	.Y(n306));
   INVX2 PlaceFE_RC_48_0 (.A(n205),
	.Y(FE_RN_25_0));
   INVX2 PlaceFE_RC_47_0 (.A(FE_OCPN18_n204),
	.Y(FE_RN_26_0));
   NAND2X1 PlaceFE_RC_46_0 (.A(FE_RN_25_0),
	.B(FE_RN_26_0),
	.Y(n383));
   AOI21X1 PlaceFE_RC_44_0 (.A(n299),
	.B(n300),
	.C(n235),
	.Y(n304));
   OR2X2 PlaceFE_RC_38_0 (.A(n132),
	.B(FE_RN_83_0),
	.Y(FE_RN_21_0));
   INVX2 PlaceFE_RC_33_0 (.A(fsm_out_select_in),
	.Y(FE_RN_18_0));
   AOI22X1 PlaceFE_RC_32_0 (.A(top_in[11]),
	.B(FE_RN_18_0),
	.C(fsm_out_select_in),
	.D(n321),
	.Y(n322));
   OAI21X1 PlaceFE_RC_31_0 (.A(FE_PSN30_n357),
	.B(FE_RN_3_0),
	.C(n291),
	.Y(n349));
   AND2X2 PlaceFE_RC_30_0 (.A(n347),
	.B(FE_RN_11_0),
	.Y(FE_RN_14_0));
   INVX2 PlaceFE_RC_29_0 (.A(FE_RN_10_0),
	.Y(FE_RN_15_0));
   OR2X2 PlaceFE_RC_22_0 (.A(n347),
	.B(n346),
	.Y(FE_RN_8_0));
   OAI21X1 PlaceFE_RC_21_0 (.A(n349),
	.B(n347),
	.C(FE_RN_8_0),
	.Y(n343));
   INVX2 PlaceFE_RC_20_0 (.A(n346),
	.Y(FE_RN_9_0));
   NOR2X1 PlaceFE_RC_19_0 (.A(FE_RN_9_0),
	.B(n73),
	.Y(FE_RN_10_0));
   INVX2 PlaceFE_RC_18_0 (.A(n73),
	.Y(FE_RN_11_0));
   INVX2 PlaceFE_RC_15_0 (.A(n255),
	.Y(FE_RN_4_0));
   NAND2X1 PlaceFE_RC_14_0 (.A(n258),
	.B(FE_RN_4_0),
	.Y(n106));
   INVX2 PlaceFE_RC_13_0 (.A(n116),
	.Y(FE_RN_5_0));
   INVX2 PlaceFE_RC_4_0 (.A(n289),
	.Y(FE_RN_0_0));
   DFFSR top_in_reg_reg_3_ (.CLK(CTS_1),
	.D(top_in[3]),
	.Q(top_in_reg[3]),
	.R(n31),
	.S(1'b1));
   DFFSR top_in_reg_reg_2_ (.CLK(CTS_1),
	.D(top_in[2]),
	.Q(top_in_reg[2]),
	.R(n31),
	.S(1'b1));
   DFFSR top_in_reg_reg_1_ (.CLK(CTS_2),
	.D(top_in[1]),
	.Q(top_in_reg[1]),
	.R(n31),
	.S(1'b1));
   DFFSR top_in_reg_reg_0_ (.CLK(CTS_5),
	.D(top_in[0]),
	.Q(top_in_reg[0]),
	.R(n31),
	.S(1'b1));
   DFFSR left_in_reg_reg_3_ (.CLK(CTS_6),
	.D(left_in[3]),
	.Q(right_out[3]),
	.R(n31),
	.S(1'b1));
   DFFSR left_in_reg_reg_2_ (.CLK(CTS_2),
	.D(left_in[2]),
	.Q(right_out[2]),
	.R(n31),
	.S(1'b1));
   DFFSR left_in_reg_reg_1_ (.CLK(CTS_2),
	.D(left_in[1]),
	.Q(right_out[1]),
	.R(n31),
	.S(1'b1));
   DFFSR left_in_reg_reg_0_ (.CLK(CTS_2),
	.D(left_in[0]),
	.Q(right_out[0]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_23_ (.CLK(CTS_7),
	.D(N25),
	.Q(accumulator_reg[23]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_22_ (.CLK(CTS_7),
	.D(N24),
	.Q(accumulator_reg[22]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_21_ (.CLK(CTS_7),
	.D(N23),
	.Q(accumulator_reg[21]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_20_ (.CLK(CTS_6),
	.D(N22),
	.Q(accumulator_reg[20]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_19_ (.CLK(CTS_10),
	.D(N21),
	.Q(accumulator_reg[19]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_18_ (.CLK(CTS_10),
	.D(N20),
	.Q(accumulator_reg[18]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_17_ (.CLK(CTS_9),
	.D(N19),
	.Q(accumulator_reg[17]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_16_ (.CLK(CTS_5),
	.D(N18),
	.Q(accumulator_reg[16]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_15_ (.CLK(CTS_5),
	.D(N17),
	.Q(accumulator_reg[15]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_14_ (.CLK(CTS_4),
	.D(N16),
	.Q(accumulator_reg[14]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_13_ (.CLK(CTS_4),
	.D(N15),
	.Q(accumulator_reg[13]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_12_ (.CLK(CTS_4),
	.D(N14),
	.Q(accumulator_reg[12]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_11_ (.CLK(CTS_4),
	.D(N13),
	.Q(accumulator_reg[11]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_10_ (.CLK(CTS_6),
	.D(N12),
	.Q(accumulator_reg[10]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_9_ (.CLK(CTS_10),
	.D(N11),
	.Q(accumulator_reg[9]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_8_ (.CLK(CTS_10),
	.D(N10),
	.Q(accumulator_reg[8]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_7_ (.CLK(CTS_6),
	.D(N9),
	.Q(accumulator_reg[7]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_6_ (.CLK(CTS_7),
	.D(N8),
	.Q(accumulator_reg[6]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_5_ (.CLK(CTS_9),
	.D(N7),
	.Q(accumulator_reg[5]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_4_ (.CLK(CTS_9),
	.D(N6),
	.Q(accumulator_reg[4]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_3_ (.CLK(CTS_9),
	.D(N5),
	.Q(accumulator_reg[3]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_2_ (.CLK(CTS_1),
	.D(N4),
	.Q(accumulator_reg[2]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_1_ (.CLK(CTS_1),
	.D(N3),
	.Q(accumulator_reg[1]),
	.R(n31),
	.S(1'b1));
   DFFSR accumulator_reg_reg_0_ (.CLK(CTS_5),
	.D(N2),
	.Q(accumulator_reg[0]),
	.R(n31),
	.S(1'b1));
   INVX1 U4 (.A(rst),
	.Y(n31));
   OR2X2 U82 (.A(n192),
	.B(n186),
	.Y(n202));
   INVX4 U83 (.A(right_out[2]),
	.Y(n186));
   OR2X2 U85 (.A(n170),
	.B(n186),
	.Y(n166));
   INVX1 U87 (.A(fsm_out_select_in),
	.Y(n252));
   OR2X2 U91 (.A(n248),
	.B(accumulator_reg[17]),
	.Y(n258));
   OR2X2 U93 (.A(n170),
	.B(n191),
	.Y(n178));
   OR2X2 U95 (.A(n109),
	.B(accumulator_reg[4]),
	.Y(n182));
   OR2X2 U96 (.A(n103),
	.B(n133),
	.Y(n234));
   OR2X2 U97 (.A(n104),
	.B(n134),
	.Y(n242));
   AND2X2 U99 (.A(n197),
	.B(n196),
	.Y(n390));
   OR2X2 U100 (.A(n196),
	.B(n197),
	.Y(n389));
   OR2X2 U101 (.A(n217),
	.B(accumulator_reg[8]),
	.Y(n228));
   OR2X2 U102 (.A(n218),
	.B(accumulator_reg[9]),
	.Y(n315));
   OR2X2 U103 (.A(n236),
	.B(accumulator_reg[12]),
	.Y(n301));
   OR2X2 U104 (.A(n222),
	.B(accumulator_reg[11]),
	.Y(n299));
   OR2X2 U105 (.A(n237),
	.B(accumulator_reg[13]),
	.Y(n307));
   OR2X2 U106 (.A(n244),
	.B(accumulator_reg[15]),
	.Y(n323));
   OR2X2 U108 (.A(n293),
	.B(accumulator_reg[19]),
	.Y(n346));
   OR2X2 U109 (.A(n295),
	.B(accumulator_reg[21]),
	.Y(n332));
   AND2X2 U110 (.A(FE_PSN29_n47),
	.B(n395),
	.Y(n397));
   AND2X2 U111 (.A(n48),
	.B(n389),
	.Y(n392));
   AND2X2 U112 (.A(n62),
	.B(n383),
	.Y(n386));
   AND2X2 U113 (.A(n114),
	.B(n377),
	.Y(n380));
   AND2X2 U114 (.A(n63),
	.B(n371),
	.Y(n373));
   AND2X2 U115 (.A(n112),
	.B(n358),
	.Y(n366));
   AND2X2 U116 (.A(n65),
	.B(n359),
	.Y(n361));
   AND2X2 U119 (.A(n252),
	.B(accumulator_reg[4]),
	.Y(bottom_out[4]));
   AND2X2 U120 (.A(n252),
	.B(accumulator_reg[5]),
	.Y(bottom_out[5]));
   AND2X2 U121 (.A(n252),
	.B(accumulator_reg[6]),
	.Y(bottom_out[6]));
   AND2X2 U122 (.A(n252),
	.B(accumulator_reg[7]),
	.Y(bottom_out[7]));
   AND2X2 U123 (.A(n252),
	.B(accumulator_reg[8]),
	.Y(bottom_out[8]));
   AND2X2 U124 (.A(n252),
	.B(accumulator_reg[9]),
	.Y(bottom_out[9]));
   AND2X2 U125 (.A(n252),
	.B(accumulator_reg[10]),
	.Y(bottom_out[10]));
   AND2X2 U126 (.A(n252),
	.B(accumulator_reg[11]),
	.Y(bottom_out[11]));
   AND2X2 U127 (.A(n252),
	.B(accumulator_reg[12]),
	.Y(bottom_out[12]));
   AND2X2 U128 (.A(n252),
	.B(accumulator_reg[13]),
	.Y(bottom_out[13]));
   AND2X2 U129 (.A(n252),
	.B(accumulator_reg[14]),
	.Y(bottom_out[14]));
   AND2X2 U130 (.A(n252),
	.B(accumulator_reg[15]),
	.Y(bottom_out[15]));
   AND2X2 U131 (.A(n252),
	.B(accumulator_reg[16]),
	.Y(bottom_out[16]));
   AND2X2 U132 (.A(n252),
	.B(accumulator_reg[17]),
	.Y(bottom_out[17]));
   AND2X2 U133 (.A(n252),
	.B(accumulator_reg[18]),
	.Y(bottom_out[18]));
   AND2X2 U134 (.A(n252),
	.B(accumulator_reg[19]),
	.Y(bottom_out[19]));
   AND2X2 U135 (.A(n252),
	.B(accumulator_reg[20]),
	.Y(bottom_out[20]));
   AND2X2 U136 (.A(n252),
	.B(accumulator_reg[21]),
	.Y(bottom_out[21]));
   AND2X2 U137 (.A(n252),
	.B(accumulator_reg[22]),
	.Y(bottom_out[22]));
   AND2X2 U138 (.A(n252),
	.B(accumulator_reg[23]),
	.Y(bottom_out[23]));
   OR2X2 U139 (.A(n74),
	.B(accumulator_reg[0]),
	.Y(n401));
   AND2X2 U140 (.A(n228),
	.B(n227),
	.Y(n272));
   OR2X2 U141 (.A(n216),
	.B(accumulator_reg[7]),
	.Y(n227));
   AND2X2 U142 (.A(n67),
	.B(n340),
	.Y(n342));
   AND2X2 U143 (.A(n66),
	.B(n287),
	.Y(n250));
   AND2X2 U144 (.A(n95),
	.B(n193),
	.Y(n396));
   OR2X2 U145 (.A(n175),
	.B(FE_RN_10),
	.Y(n188));
   OR2X2 U146 (.A(n192),
	.B(FE_RN_10),
	.Y(n400));
   AND2X2 U147 (.A(accumulator_reg[0]),
	.B(n74),
	.Y(n402));
   AND2X2 U149 (.A(accumulator_reg[7]),
	.B(n216),
	.Y(n352));
   OR2X2 U150 (.A(n175),
	.B(n186),
	.Y(n169));
   AND2X2 U152 (.A(accumulator_reg[8]),
	.B(n217),
	.Y(n229));
   OR2X2 U154 (.A(n105),
	.B(n132),
	.Y(n255));
   AND2X2 U155 (.A(n227),
	.B(n111),
	.Y(n353));
   AND2X2 U156 (.A(n60),
	.B(n332),
	.Y(n296));
   AND2X2 U157 (.A(n51),
	.B(n317),
	.Y(n319));
   AND2X2 U158 (.A(n57),
	.B(n325),
	.Y(n327));
   AND2X2 U159 (.A(n53),
	.B(n301),
	.Y(n303));
   AND2X2 U160 (.A(n54),
	.B(n307),
	.Y(n268));
   AND2X2 U161 (.A(n50),
	.B(n315),
	.Y(n274));
   AND2X2 U162 (.A(FE_RN_75_0),
	.B(n323),
	.Y(n280));
   AND2X2 U163 (.A(n58),
	.B(n258),
	.Y(n260));
   AND2X2 U164 (.A(n59),
	.B(n346),
	.Y(n348));
   AND2X2 U165 (.A(n52),
	.B(n299),
	.Y(n223));
   AND2X2 U166 (.A(n49),
	.B(n228),
	.Y(n230));
   AND2X2 U167 (.A(n55),
	.B(n309),
	.Y(n311));
   OR2X2 U168 (.A(n193),
	.B(n95),
	.Y(n395));
   INVX2 U187 (.A(n396),
	.Y(n47));
   INVX1 U188 (.A(n390),
	.Y(n48));
   INVX1 U189 (.A(n229),
	.Y(n49));
   AND2X2 U190 (.A(accumulator_reg[9]),
	.B(n218),
	.Y(n273));
   INVX1 U191 (.A(n273),
	.Y(n50));
   AND2X2 U192 (.A(accumulator_reg[10]),
	.B(n219),
	.Y(n318));
   INVX1 U193 (.A(n318),
	.Y(n51));
   AND2X2 U194 (.A(accumulator_reg[11]),
	.B(n222),
	.Y(n235));
   INVX1 U195 (.A(n235),
	.Y(n52));
   AND2X2 U196 (.A(accumulator_reg[12]),
	.B(n236),
	.Y(n302));
   INVX1 U197 (.A(n302),
	.Y(n53));
   AND2X2 U198 (.A(accumulator_reg[13]),
	.B(n237),
	.Y(n267));
   INVX1 U199 (.A(n267),
	.Y(n54));
   AND2X2 U200 (.A(accumulator_reg[14]),
	.B(n238),
	.Y(n310));
   INVX1 U201 (.A(n310),
	.Y(n55));
   AND2X2 U202 (.A(accumulator_reg[15]),
	.B(n244),
	.Y(n279));
   AND2X2 U204 (.A(accumulator_reg[16]),
	.B(n245),
	.Y(n326));
   INVX1 U205 (.A(n326),
	.Y(n57));
   AND2X2 U206 (.A(accumulator_reg[17]),
	.B(n248),
	.Y(n259));
   INVX1 U207 (.A(n259),
	.Y(n58));
   AND2X2 U208 (.A(accumulator_reg[19]),
	.B(n293),
	.Y(n347));
   INVX1 U209 (.A(n347),
	.Y(n59));
   AND2X2 U210 (.A(accumulator_reg[21]),
	.B(n295),
	.Y(n331));
   INVX1 U211 (.A(n331),
	.Y(n60));
   INVX1 U215 (.A(n372),
	.Y(n63));
   INVX1 U218 (.A(n360),
	.Y(n65));
   AND2X2 U219 (.A(n214),
	.B(n213),
	.Y(n360));
   INVX1 U220 (.A(n285),
	.Y(n66));
   AND2X2 U221 (.A(accumulator_reg[18]),
	.B(n249),
	.Y(n285));
   INVX1 U222 (.A(n341),
	.Y(n67));
   AND2X2 U223 (.A(accumulator_reg[20]),
	.B(n294),
	.Y(n341));
   INVX1 U226 (.A(n402),
	.Y(n70));
   OR2X2 U228 (.A(n211),
	.B(n212),
	.Y(n358));
   INVX1 U229 (.A(n227),
	.Y(n72));
   OR2X2 U230 (.A(n294),
	.B(accumulator_reg[20]),
	.Y(n340));
   INVX1 U231 (.A(n340),
	.Y(n73));
   INVX2 U232 (.A(n400),
	.Y(n74));
   INVX1 U236 (.A(n230),
	.Y(n78));
   INVX1 U239 (.A(n268),
	.Y(n81));
   INVX1 U241 (.A(n280),
	.Y(n83));
   INVX1 U242 (.A(n296),
	.Y(n84));
   INVX1 U243 (.A(n348),
	.Y(n85));
   INVX1 U246 (.A(n319),
	.Y(n88));
   INVX1 U248 (.A(n342),
	.Y(n90));
   INVX1 U249 (.A(n353),
	.Y(n91));
   INVX2 U254 (.A(n194),
	.Y(n95));
   OR2X2 U255 (.A(n192),
	.B(n190),
	.Y(n194));
   INVX2 U256 (.A(n242),
	.Y(n96));
   INVX2 U257 (.A(n234),
	.Y(n97));
   INVX1 U263 (.A(n272),
	.Y(n103));
   INVX1 U264 (.A(n266),
	.Y(n104));
   AND2X2 U265 (.A(n301),
	.B(n299),
	.Y(n266));
   AND2X2 U266 (.A(n96),
	.B(n97),
	.Y(n278));
   INVX1 U267 (.A(n278),
	.Y(n105));
   INVX1 U269 (.A(n168),
	.Y(n107));
   OR2X2 U270 (.A(n170),
	.B(n171),
	.Y(n168));
   INVX4 U271 (.A(n203),
	.Y(n108));
   OR2X2 U272 (.A(FE_PSN31_n190),
	.B(n187),
	.Y(n203));
   INVX4 U273 (.A(n169),
	.Y(n109));
   INVX1 U275 (.A(n352),
	.Y(n111));
   INVX1 U278 (.A(n377),
	.Y(n113));
   INVX1 U280 (.A(n359),
	.Y(n115));
   OR2X2 U281 (.A(n213),
	.B(n214),
	.Y(n359));
   INVX1 U282 (.A(n287),
	.Y(n116));
   OR2X2 U283 (.A(n249),
	.B(accumulator_reg[18]),
	.Y(n287));
   INVX1 U288 (.A(n392),
	.Y(n122));
   INVX1 U289 (.A(n397),
	.Y(n123));
   INVX1 U291 (.A(n380),
	.Y(n125));
   INVX1 U292 (.A(n386),
	.Y(n126));
   INVX1 U293 (.A(n366),
	.Y(n127));
   INVX1 U294 (.A(n373),
	.Y(n128));
   INVX1 U295 (.A(n361),
	.Y(n129));
   AND2X2 U298 (.A(n325),
	.B(n323),
	.Y(n247));
   INVX1 U299 (.A(n247),
	.Y(n132));
   OR2X2 U300 (.A(n245),
	.B(accumulator_reg[16]),
	.Y(n325));
   AND2X2 U301 (.A(n317),
	.B(n315),
	.Y(n221));
   INVX2 U302 (.A(n221),
	.Y(n133));
   OR2X2 U303 (.A(n219),
	.B(accumulator_reg[10]),
	.Y(n317));
   AND2X2 U304 (.A(n309),
	.B(n307),
	.Y(n240));
   INVX1 U305 (.A(n240),
	.Y(n134));
   OR2X2 U306 (.A(n238),
	.B(accumulator_reg[14]),
	.Y(n309));
   INVX4 U307 (.A(n202),
	.Y(n135));
   MUX2X1 U332 (.A(FE_OCPN20_top_in_reg_2),
	.B(accumulator_reg[2]),
	.S(fsm_out_select_in),
	.Y(n161));
   INVX1 U333 (.A(n161),
	.Y(bottom_out[2]));
   MUX2X1 U334 (.A(FE_OCPN19_top_in_reg_3),
	.B(FE_PSN28_accumulator_reg_3),
	.S(fsm_out_select_in),
	.Y(n162));
   INVX1 U335 (.A(n162),
	.Y(bottom_out[3]));
   MUX2X1 U336 (.A(FE_OCPN22_top_in_reg_0),
	.B(accumulator_reg[0]),
	.S(fsm_out_select_in),
	.Y(n163));
   INVX1 U337 (.A(n163),
	.Y(bottom_out[0]));
   MUX2X1 U338 (.A(FE_PSN24_top_in_reg_1),
	.B(accumulator_reg[1]),
	.S(fsm_out_select_in),
	.Y(n164));
   INVX1 U339 (.A(n164),
	.Y(bottom_out[1]));
   INVX2 U340 (.A(top_in_reg[2]),
	.Y(n175));
   INVX4 U341 (.A(top_in_reg[3]),
	.Y(n170));
   INVX4 U342 (.A(right_out[3]),
	.Y(n171));
   OR2X2 U343 (.A(n175),
	.B(n171),
	.Y(n165));
   OR2X2 U347 (.A(n187),
	.B(n171),
	.Y(n173));
   FAX1 U348 (.A(accumulator_reg[5]),
	.B(n166),
	.C(n165),
	.YC(n167),
	.YS(n181));
   FAX1 U349 (.A(accumulator_reg[6]),
	.B(n107),
	.C(n167),
	.YC(n213),
	.YS(n212));
   INVX1 U350 (.A(accumulator_reg[7]),
	.Y(n214));
   INVX4 U352 (.A(top_in_reg[0]),
	.Y(n192));
   OR2X2 U353 (.A(n192),
	.B(n171),
	.Y(n177));
   FAX1 U354 (.A(n174),
	.B(n173),
	.C(n172),
	.YC(n180),
	.YS(n183));
   FAX1 U356 (.A(n136),
	.B(n178),
	.C(n177),
	.YC(n184),
	.YS(n198));
   FAX1 U357 (.A(n182),
	.B(n181),
	.C(n180),
	.YC(n211),
	.YS(n208));
   FAX1 U358 (.A(n185),
	.B(n184),
	.C(n183),
	.YC(n209),
	.YS(n206));
   FAX1 U364 (.A(n200),
	.B(n199),
	.C(n198),
	.YC(n207),
	.YS(n204));
   FAX1 U365 (.A(n108),
	.B(n135),
	.C(n201),
	.YC(n205),
	.YS(n196));
   OAI21X1 U369 (.A(n115),
	.B(n112),
	.C(n65),
	.Y(n290));
   INVX1 U370 (.A(n290),
	.Y(n215));
   INVX1 U372 (.A(accumulator_reg[9]),
	.Y(n217));
   INVX1 U373 (.A(accumulator_reg[8]),
	.Y(n216));
   INVX1 U374 (.A(accumulator_reg[11]),
	.Y(n219));
   INVX1 U375 (.A(accumulator_reg[10]),
	.Y(n218));
   AOI21X1 U376 (.A(n228),
	.B(n352),
	.C(n229),
	.Y(n271));
   AOI21X1 U377 (.A(n317),
	.B(n273),
	.C(n318),
	.Y(n220));
   OAI21X1 U378 (.A(n133),
	.B(n271),
	.C(n220),
	.Y(n243));
   AOI21X1 U379 (.A(n97),
	.B(n226),
	.C(n243),
	.Y(n265));
   INVX2 U380 (.A(n265),
	.Y(n300));
   INVX1 U381 (.A(accumulator_reg[12]),
	.Y(n222));
   MUX2X1 U383 (.A(n224),
	.B(top_in[12]),
	.S(fsm_out_select_in),
	.Y(n225));
   INVX1 U384 (.A(n225),
	.Y(N14));
   OAI21X1 U385 (.A(n72),
	.B(n354),
	.C(n111),
	.Y(n231));
   XNOR2X1 U386 (.A(n231),
	.B(n78),
	.Y(n232));
   MUX2X1 U387 (.A(n232),
	.B(top_in[9]),
	.S(fsm_out_select_in),
	.Y(n233));
   INVX1 U388 (.A(n233),
	.Y(N11));
   INVX1 U389 (.A(accumulator_reg[18]),
	.Y(n248));
   INVX1 U390 (.A(accumulator_reg[13]),
	.Y(n236));
   INVX2 U391 (.A(accumulator_reg[15]),
	.Y(n238));
   INVX1 U392 (.A(accumulator_reg[14]),
	.Y(n237));
   INVX1 U393 (.A(accumulator_reg[17]),
	.Y(n245));
   INVX1 U394 (.A(accumulator_reg[16]),
	.Y(n244));
   AOI21X1 U395 (.A(n301),
	.B(n235),
	.C(n302),
	.Y(n264));
   AOI21X1 U396 (.A(n309),
	.B(n267),
	.C(n310),
	.Y(n239));
   OAI21X1 U397 (.A(n134),
	.B(n264),
	.C(n239),
	.Y(n241));
   AOI21X1 U398 (.A(n243),
	.B(n96),
	.C(n241),
	.Y(n277));
   AOI21X1 U399 (.A(n325),
	.B(n279),
	.C(n326),
	.Y(n246));
   OAI21X1 U400 (.A(n132),
	.B(n277),
	.C(n246),
	.Y(n256));
   OAI21X1 U402 (.A(n106),
	.B(n354),
	.C(n286),
	.Y(n251));
   INVX1 U403 (.A(accumulator_reg[19]),
	.Y(n249));
   MUX2X1 U405 (.A(n253),
	.B(top_in[19]),
	.S(fsm_out_select_in),
	.Y(n254));
   INVX1 U406 (.A(n254),
	.Y(N21));
   INVX1 U407 (.A(n256),
	.Y(n257));
   OAI21X1 U408 (.A(n255),
	.B(n354),
	.C(n257),
	.Y(n261));
   MUX2X1 U410 (.A(n262),
	.B(top_in[18]),
	.S(fsm_out_select_in),
	.Y(n263));
   INVX1 U411 (.A(n263),
	.Y(N20));
   XNOR2X1 U413 (.A(n308),
	.B(n81),
	.Y(n269));
   MUX2X1 U414 (.A(n269),
	.B(top_in[14]),
	.S(fsm_out_select_in),
	.Y(n270));
   INVX1 U415 (.A(n270),
	.Y(N16));
   MUX2X1 U418 (.A(n275),
	.B(top_in[10]),
	.S(fsm_out_select_in),
	.Y(n276));
   INVX1 U419 (.A(n276),
	.Y(N12));
   XNOR2X1 U421 (.A(n324),
	.B(n83),
	.Y(n281));
   MUX2X1 U422 (.A(n281),
	.B(top_in[16]),
	.S(fsm_out_select_in),
	.Y(n282));
   INVX1 U423 (.A(n282),
	.Y(N18));
   INVX1 U424 (.A(accumulator_reg[21]),
	.Y(n294));
   AOI21X1 U426 (.A(n290),
	.B(FE_RN_0_0),
	.C(n288),
	.Y(n291));
   INVX1 U428 (.A(accumulator_reg[20]),
	.Y(n293));
   INVX1 U431 (.A(accumulator_reg[22]),
	.Y(n295));
   XNOR2X1 U432 (.A(n333),
	.B(n84),
	.Y(n297));
   INVX1 U434 (.A(n298),
	.Y(N24));
   INVX1 U438 (.A(n306),
	.Y(N15));
   INVX1 U440 (.A(n314),
	.Y(N17));
   AOI21X1 U441 (.A(n315),
	.B(FE_RN_3),
	.C(n273),
	.Y(n320));
   XOR2X1 U442 (.A(n320),
	.B(n88),
	.Y(n321));
   INVX2 U444 (.A(n322),
	.Y(N13));
   INVX1 U448 (.A(n330),
	.Y(N19));
   INVX1 U451 (.A(accumulator_reg[23]),
	.Y(n335));
   XOR2X1 U452 (.A(n335),
	.B(accumulator_reg[22]),
	.Y(n336));
   XOR2X1 U453 (.A(n337),
	.B(n336),
	.Y(n338));
   INVX1 U454 (.A(n339),
	.Y(N25));
   XOR2X1 U455 (.A(n343),
	.B(n90),
	.Y(n344));
   MUX2X1 U456 (.A(n344),
	.B(top_in[21]),
	.S(fsm_out_select_in),
	.Y(n345));
   INVX1 U457 (.A(n345),
	.Y(N23));
   XNOR2X1 U458 (.A(n349),
	.B(n85),
	.Y(n350));
   MUX2X1 U459 (.A(n350),
	.B(top_in[20]),
	.S(fsm_out_select_in),
	.Y(n351));
   INVX1 U460 (.A(n351),
	.Y(N22));
   XOR2X1 U461 (.A(FE_OCPN17_n354),
	.B(n91),
	.Y(n355));
   MUX2X1 U462 (.A(n355),
	.B(top_in[8]),
	.S(fsm_out_select_in),
	.Y(n356));
   INVX2 U463 (.A(n356),
	.Y(N10));
   INVX1 U464 (.A(FE_PSN30_n357),
	.Y(n367));
   AOI21X1 U465 (.A(n367),
	.B(n358),
	.C(n365),
	.Y(n362));
   XOR2X1 U466 (.A(n362),
	.B(n129),
	.Y(n363));
   MUX2X1 U467 (.A(n363),
	.B(top_in[7]),
	.S(fsm_out_select_in),
	.Y(n364));
   INVX1 U468 (.A(n364),
	.Y(N9));
   XNOR2X1 U469 (.A(n367),
	.B(n127),
	.Y(n368));
   MUX2X1 U470 (.A(n368),
	.B(top_in[6]),
	.S(fsm_out_select_in),
	.Y(n369));
   INVX1 U471 (.A(n369),
	.Y(N8));
   INVX1 U472 (.A(n370),
	.Y(n379));
   OAI21X1 U473 (.A(n113),
	.B(n379),
	.C(n114),
	.Y(n374));
   XNOR2X1 U474 (.A(n374),
	.B(n128),
	.Y(n375));
   MUX2X1 U475 (.A(n375),
	.B(top_in[5]),
	.S(fsm_out_select_in),
	.Y(n376));
   INVX1 U476 (.A(n376),
	.Y(N7));
   XOR2X1 U477 (.A(n125),
	.B(n379),
	.Y(n381));
   MUX2X1 U478 (.A(n381),
	.B(top_in[4]),
	.S(fsm_out_select_in),
	.Y(n382));
   INVX1 U479 (.A(n382),
	.Y(N6));
   XOR2X1 U480 (.A(n126),
	.B(FE_RN_5),
	.Y(n387));
   MUX2X1 U481 (.A(n387),
	.B(top_in[3]),
	.S(fsm_out_select_in),
	.Y(n388));
   INVX1 U482 (.A(n388),
	.Y(N5));
   XNOR2X1 U483 (.A(n122),
	.B(FE_PSN26_FE_RN_4),
	.Y(n393));
   MUX2X1 U484 (.A(n393),
	.B(top_in[2]),
	.S(fsm_out_select_in),
	.Y(n394));
   INVX1 U485 (.A(n394),
	.Y(N4));
   XNOR2X1 U486 (.A(n123),
	.B(n402),
	.Y(n398));
   MUX2X1 U487 (.A(n398),
	.B(top_in[1]),
	.S(fsm_out_select_in),
	.Y(n399));
   INVX1 U488 (.A(n399),
	.Y(N3));
   AND2X2 U489 (.A(n70),
	.B(n401),
	.Y(n403));
   MUX2X1 U490 (.A(n403),
	.B(top_in[0]),
	.S(fsm_out_select_in),
	.Y(n404));
   INVX1 U491 (.A(n404),
	.Y(N2));
endmodule

